# Generated by Django 5.0 on 2024-03-05 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CollegeEvents',
            new_name='CollegeEvent',
        ),
    ]
